sitegroup: wcet_wiche_edu

deploy_tasks:
  development:
    before_deploy:
      - cd docroot; rm -rf vendor
    after_deploy:
      - cd docroot; drush -y updb --cache-clear=0
      - cd docroot; drush -y cr all
  production:
    before_deploy:
      - cd docroot; rm -rf vendor
    after_deploy:
      - cd docroot; drush -y updb --cache-clear=0
      - cd docroot; drush -y cr all

shared:
  production:
    - src: files
      dst: docroot/sites/default/files
