sitegroup: wcet_wiche_edu

deploy_tasks:
  development:
    before_deploy:
      - composer install
    after_deploy:
      - drush -y updb --cache-clear=0
      - drush -y cc all
  production:
    after_deploy:
      - drush -y updb --cache-clear=0
      - drush -y cc all

shared:
  production:
    - src: files
      dst: docroot/sites/default/files
      
      
